language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t cdfairchild/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cdfairchild/react-test npm test

after_success:
  - docker build -t cdfairchild/multi-client ./client 
  - docker build -t cdfairchild/multi-nginx ./nginx 
  - docker build -t cdfairchild/multi-server ./server 
  - docker build -t cdfairchild/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cdfairchild/multi-client
  - docker push cdfairchild/multi-nginx
  - docker push cdfairchild/multi-server
  - docker push cdfairchild/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-128936874023
  bucker_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
